= Aiz's NIU Mini layout

// URIs:
:uri-niu-mini: https://kbdfans.com/products/niu-mini-40-diy-kit
:uri-colemak: https://colemak.com
:uri-eurkey: https://eurkey.steffen.bruentjen.eu
:uri-qmk-doc: https://docs.qmk.fm/#
:uri-qmk-newbs: {uri-qmk-doc}/newbs
:uri-qmk-setup: {uri-qmk-doc}/newbs_getting_started
:uri-qmk-git-niu-mini: https://github.com/qmk/qmk_firmware/tree/master/keyboards/niu_mini/keymaps


== What is this?
My personal keyboard layout for the {uri-niu-mini}[NIU Mini].

This is based on the {uri-colemak}[colemak] layout since I like it more than qwerty.

Sometimes I write in Swedish and need the nordic characters for that. I solve this by using the {uri-eurkey}[EurKEY] layout.

The NIU Mini can run QMK firmware and this layout is made with QMK. If you don't know what QMK is read the next section.

== What is QMK
QMK firmware is the software that runs on your keyboard.

If you are brand new to QMK, check out the {uri-qmk-doc}[documentation] and the {uri-qmk-newbs}[Complete Newbs Guide].

To build QMK keymaps you need to setup your QMK environment. See the {uri-qmk-setup}[setup tutorial] on how to do that.

== Build and flash
I don't actually recommend flashing this layout, instead use it as inspiration for your own.
Check out the included {uri-qmk-git-niu-mini}[NIU Mini layouts] if you haven't already.

.Prerequisites
- QMK environment
- A NIU Mini keyboard

Clone or download this repository.
----
git clone https://github.com/Aiz0/NIU-Mini-keymap
----
Create a new directory for the keymap in the QMK NIU Mini keymaps folder.

----
mkdir $QMK_HOME/keyboards/niu_mini/keymaps/aiz
----

Copy the necessary files to the new directory you made.

.Files to copy
- keymap.c
- config.h

Compile the layout.
----
qmk compile -kb niu_mini -km aiz
----

Finally flash the layout.
----
qmk flash -kb niu_mini -km aiz
----
